name: PvP
description: PvP mini game
authors: [ StarTux ]
version: 0.1-SNAPSHOT
api-version: 1.13
website: https://cavetale.com
main: com.winthier.minigames.pvp.PvP
depend: [ SQL, Connect ]
softdepend: []
commands:
  colorfall:
    aliases: [ready, tp, highscore, hi, quit]
permissions: {}
